version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret  # postgres:secret
    ports:
      - 5432:5432

  datadog:
    image: datadog/agent
    environment:
     - DD_API_KEY
     - DD_SITE=datadoghq.eu
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
      - 8126:8126
